#!/usr/bin/env php
<?php declare(strict_types=1);

if(php_sapi_name()!= "cli")
{
  fwrite(STDERR,
  PHP_EOL."Fichier uniquement pour ligne de commande".PHP_EOL);
  die(1);
}

//Récupération des valeur de notre fichier .env
$dbname = getenv('MYSQL_DATABASE');
$dbuser = getenv('MYSQL_USER');
$dbpassword = getenv('MYSQL_PASSWORD');
$dbcontainer = getenv('CONTAINER_MYSQL');

$pdo = new \PDO("mysql:host=$dbcontainer;dbname=$dbname", $dbuser, $dbpassword);

/**
* Suppression de table
*/ 
$pdo->exec('SET FOREIGN_KEY_CHECKS = 0');

$pdo->exec('DROP TABLE best_record');

$pdo->exec('SET FOREIGN_KEY_CHECKS = 1');

/**
 * creation tables
 * 
 */
echo "[";
$pdo->exec("CREATE TABLE best_record(
  id INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  timer INT NOT NULL,
  PRIMARY KEY(id)
)");

echo "||||]
";